### ISSUE TITLE
[AWS] Handle 5 minute expiration on AWS S3 Policies

### ISSUE THREAD

**Issue by brandonhub** [froala/wysiwyg-editor-php-sdk#18]
Hello! We would like to implement image upload with the Froala editor and we've semi-successfully accomplished this by following [this tutorial](https://www.froala.com/wysiwyg-editor/docs/sdks/php/image-s3-upload). However, we've run into a small snag. Image upload only seems to work within 5 minutes of initializing the Froala editor. Any uploads that are attempted after the 5 minutes have elapsed will fail with a `<Code>AccessDenied</Code><Message>Invalid according to Policy: Policy expired.</Message>` error message.

I suspect this behavior is due to [this line](https://github.com/froala/wysiwyg-editor-php-sdk/blob/749aca2d5ca0fdb821130da60dbe671aeef06a75/lib/FroalaEditor/S3.php#L69), which seems to be hardcoded within the PHP sdk without the ability to customize it with a parameter or config of any sort.

Is there a way to handle this 5 min policy expiration or perhaps configure the timeout period from outside the php sdk? Thanks!

**Comment by shreypasari-accolite** [comment]
hi @stefanneculai 
I am not able to reproduce the error, can you help me it how to reproduce.
Thanks

**Comment by stefanneculai** [comment]
@shreypasari-accolite sure:
- generate a signature and open a page with the editor that is set to upload to S3
- wait more than 5 minutes and image upload would not be working anymore

**Comment by mohit18513** [comment]
Hi @stefanneculai,  is it manadatory to use same hash for subsequent uploads or is there way to generate new hash whenever image upload happens? 
Thanks
Mohit

**Comment by stefanneculai** [comment]
To test https://github.com/froala/wysiwyg-editor-php-sdk/issues/18#issuecomment-466976967, yes you should be using the same hash.

**Comment by mohit18513** [comment]
Thanks @stefanneculai. We are using private bucket and when we are generating hash (acl- private)using java and passing it to imageUploadToS3 attribute then image is getting uploaded on S3 and in response we are getting image url which is not accessible since bucket is private.
Can you please help me to know what we need to with returned url to make it accressible? 

Also we are using elixir in backend and we want to generate hash using elixir and somehow correct hash is not being generated due to which   image does not get upload on S3. Can you please share some sample code of generating s3hash using elixir as well?

**Comment by stefanneculai** [comment]
@mohit18513 please make sure that you set the right CORS policy for your bucket. Also, you should make the images accessible to everyone (public) so that they can be accessed. Unfortunately, we're not familiar with Elixir in order to help more on it.

**Comment by mohit18513** [comment]
@stefanneculai,  our bucket is private and we can not make it public as we can not make images accessible to everyone. 
Can you please confirm that froala s3 image upload functionality works only with public bucket and it can not be used with private bucket?

**Comment by drfraker** [comment]
@mohit18513 Did you find a solution to the "private images" problem? I'm looking at this editor but it seems that images must be public in order for it to work.

**Comment by mohit18513** [comment]
Hi,
Yes, we had solved this problem.
We had used imageUploadUrl attribue to upload image on s3.
We had passed api url in imageUploadUrl and then in backend, we generated
s3 presigned upload url and download url. Upload url is used to image on s3
private bucket. Once the image is uploaded on s3 then we returned the
download url which is further used by froala editor to show image in
editor.
Please let me know if you have any questions.
Thanks.
