### ISSUE TITLE
Amazon S3 upload shows error "undefined"

### ISSUE THREAD

**Issue by kevinkt** [froala/wysiwyg-editor-php-sdk#19]
I am trying to set-up Amazon S3 upload, the resulting error says 

VM459:1 OPTIONS https://undefined.amazonaws.com/undefined net::ERR_NAME_NOT_RESOLVED

Any idea why this might be happening? 

CORS is set-up, my credentials are valid.

**Comment by stefanneculai** [comment]
It looks like you are not setting it correctly. Make sure you follow the example:
https://github.com/froala/editor-php-sdk-example/blob/337c5e61489e68779e805e2dc0759b2d567b7b88/index.php#L12
https://github.com/froala/editor-php-sdk-example/blob/337c5e61489e68779e805e2dc0759b2d567b7b88/index.php#L322
